# Generated by Django 5.2.12 on 2026-03-15 03:46

import cursos.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.CharField(max_length=150, null=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=2)),
                ('zona', models.CharField(blank=True, choices=[('CEN', 'CENTRAL'), ('CDMX', 'CD. DE MEX.'), ('PUE', 'PUEBLA, PUE.'), ('XAL', 'XALAPA, VER.'), ('MIS', 'MISANTLA, VER.'), ('ALT', 'ALTOTONGA, VER.'), ('JUC', 'JUCHIQUE DE FERRER, VER.'), ('POZ', 'POZA RICA, VER.'), ('CUE', 'CUERNAVACA, MOR.'), ('URU', 'URUAPAN, MICH.'), ('CAR', 'CARDENAS, TAB.'), ('GDL', 'GUADALAJARA, JAL.'), ('SIL', 'SILAO, GTO.'), ('PAC', 'PACHUCA, HGO.'), ('CAN', 'CANCÚN, Q. R.'), ('JUA', 'CIUDAD JUÁREZ, CHIH.'), ('MAT', 'MATÍAS ROMERO, OAX.'), ('CHP', 'CHILPANCINGO, GRO.'), ('TIJ', 'TIJUANA, B.C.'), ('REY', 'REYNOSA, TAMPS.'), ('TOL', 'TOLUCA, EDO. DE MEX.'), ('OAX', 'OAXACA, OAX.'), ('ELG', 'ELGIN ILLINOIS, EUA'), ('TAP', 'TAPACHULA, CHIS.'), ('CAB', 'CABO SAN LUCAS, B.C.S.'), ('TEZ', 'TEZIUTLÁN, PUE.'), ('TAM', 'TAMPICO, TAMPS.'), ('VER', 'VERACRUZ, VER.'), ('TOP', 'TOPILEJO, CD. MEX.'), ('NEZ', 'CIUDAD NEZAHUALCÓYOTL, EDOMEX'), ('MIR', 'MIRAFLORES, EDOMEX'), ('CAL', 'CALPULALPAN, TLAX.'), ('COY', 'COYOTEPEC, EDOMEX'), ('CSU', 'CENTRO Y SUDAMÉRICA')], max_length=100, null=True)),
                ('subzona', models.CharField(blank=True, max_length=100, null=True)),
                ('otra_denominacion', models.BooleanField(default=False)),
                ('denominacion', models.CharField(blank=True, max_length=150, null=True)),
                ('iglesia', models.CharField(blank=True, max_length=150, null=True)),
                ('pastor', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('grado', models.CharField(choices=[('MIN', 'MINISTRO / DIACONISA'), ('EG_ESC', 'EGRESADO DEL I.T.E. (Sistema Escolarizado)'), ('EG_AB', 'EGRESADO DEL I.T.E. (Sistema Abierto)'), ('EST_1E', 'ESTUDIANTE (PRIMER AÑO) S.E.'), ('EST_2E', 'ESTUDIANTE (SEGUNDO AÑO) S.E.'), ('EST_3E', 'ESTUDIANTE (TERCER AÑO) S.E.'), ('EST_1A', 'ESTUDIANTE (PRIMER AÑO) S. ABIERTO'), ('EST_2A', 'ESTUDIANTE (SEGUNDO AÑO) S. ABIERTO'), ('EST_3A', 'ESTUDIANTE (TERCER AÑO) S. ABIERTO'), ('EST_4A', 'ESTUDIANTE (CUARTO AÑO) S. ABIERTO'), ('OBR', 'OBRERO LAICO'), ('ANC', 'ANCIANO DE IGLESIA'), ('OTR', 'OTRO (ESPECIFICAR)'), ('REP_Z', 'REPRESENTANTE DE ZONA'), ('REP_S', 'REPRESENTANTE DE SUB ZONA'), ('EG_XE', 'EGRESADO ITE CAMPUS XALAPA S. ESCOLARIZADO'), ('EG_XA', 'EGRESADO ITE CAMPUS XALAPA S. ABIERTO'), ('EG_SE', 'EGRESADO ITE CAMPUS SURESTE S. ESCOLARIZADO'), ('EG_EL', 'EGRESADO ITE CAMPUS ELGIN, IL'), ('SIN_R', 'SIN RANGO')], max_length=100)),
                ('periodo', models.CharField(max_length=50, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to=cursos.models.qr_upload_path)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('asistio', models.BooleanField(default=True)),
                ('inscrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='cursos.inscrito')),
            ],
            options={
                'indexes': [models.Index(fields=['fecha'], name='cursos_asis_fecha_514709_idx'), models.Index(fields=['inscrito'], name='cursos_asis_inscrit_9f1a26_idx')],
                'unique_together': {('inscrito', 'fecha')},
            },
        ),
    ]
