# Generated by Django 5.2.12 on 2026-03-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='grado',
            field=models.CharField(choices=[('MIN', 'MINISTRO / DIACONISA'), ('EG_ESC', 'EGRESADO DEL I.T.E. (Sistema Escolarizado)'), ('EG_AB', 'EGRESADO DEL I.T.E. (Sistema Abierto)'), ('EST_1E', 'ESTUDIANTE (PRIMER ANO) S.E.'), ('EST_2E', 'ESTUDIANTE (SEGUNDO ANO) S.E.'), ('EST_3E', 'ESTUDIANTE (TERCER ANO) S.E.'), ('EST_1A', 'ESTUDIANTE (PRIMER ANO) S. ABIERTO'), ('EST_2A', 'ESTUDIANTE (SEGUNDO ANO) S. ABIERTO'), ('EST_3A', 'ESTUDIANTE (TERCER ANO) S. ABIERTO'), ('EST_4A', 'ESTUDIANTE (CUARTO ANO) S. ABIERTO'), ('OBR', 'OBRERO LAICO'), ('ANC', 'ANCIANO DE IGLESIA'), ('OTR', 'OTRO (ESPECIFICAR)'), ('REP_Z', 'REPRESENTANTE DE ZONA'), ('REP_S', 'REPRESENTANTE DE SUB ZONA'), ('EG_XE', 'EGRESADO ITE CAMPUS XALAPA S. ESCOLARIZADO'), ('EG_XA', 'EGRESADO ITE CAMPUS XALAPA S. ABIERTO'), ('EG_SE', 'EGRESADO ITE CAMPUS SURESTE S. ESCOLARIZADO'), ('EG_EL', 'EGRESADO ITE CAMPUS ELGIN, IL'), ('SIN_R', 'SIN RANGO')], max_length=100),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='periodo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='zona',
            field=models.CharField(blank=True, choices=[('CEN', 'CENTRAL'), ('CDMX', 'CD. DE MEX.'), ('PUE', 'PUEBLA, PUE.'), ('XAL', 'XALAPA, VER.'), ('MIS', 'MISANTLA, VER.'), ('ALT', 'ALTOTONGA, VER.'), ('JUC', 'JUCHIQUE DE FERRER, VER.'), ('POZ', 'POZA RICA, VER.'), ('CUE', 'CUERNAVACA, MOR.'), ('URU', 'URUAPAN, MICH.'), ('CAR', 'CARDENAS, TAB.'), ('GDL', 'GUADALAJARA, JAL.'), ('SIL', 'SILAO, GTO.'), ('PAC', 'PACHUCA, HGO.'), ('CAN', 'CANCUN, Q. R.'), ('JUA', 'CIUDAD JUAREZ, CHIH.'), ('MAT', 'MATIAS ROMERO, OAX.'), ('CHP', 'CHILPANCINGO, GRO.'), ('TIJ', 'TIJUANA, B.C.'), ('REY', 'REYNOSA, TAMPS.'), ('TOL', 'TOLUCA, EDO. DE MEX.'), ('OAX', 'OAXACA, OAX.'), ('ELG', 'ELGIN ILLINOIS, EUA'), ('TAP', 'TAPACHULA, CHIS.'), ('CAB', 'CABO SAN LUCAS, B.C.S.'), ('TEZ', 'TEZIUTLAN, PUE.'), ('TAM', 'TAMPICO, TAMPS.'), ('VER', 'VERACRUZ, VER.'), ('TOP', 'TOPILEJO, CD. MEX.'), ('NEZ', 'CIUDAD NEZAHUALCOYOTL, EDOMEX'), ('MIR', 'MIRAFLORES, EDOMEX'), ('CAL', 'CALPULALPAN, TLAX.'), ('COY', 'COYOTEPEC, EDOMEX'), ('CSU', 'CENTRO Y SUDAMERICA')], max_length=100, null=True),
        ),
    ]
