# Generated by Django 5.2.12 on 2026-03-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_inscrito_grado_alter_inscrito_monto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrito',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
