# Generated by Django 5.2.12 on 2026-04-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_inscrito_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrito',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
