# Generated by Django 5.2.12 on 2026-03-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_operador',
            field=models.BooleanField(default=False),
        ),
    ]
