# Generated by Django 5.2.12 on 2026-03-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_user_is_operador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresa'},
        ),
        migrations.AddField(
            model_name='company',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_small',
            field=models.ImageField(blank=True, help_text='Logo cuadrado/ícono para móvil y favicon (recomendado 512×512 px)', null=True, upload_to='company/logo/'),
        ),
        migrations.AddField(
            model_name='company',
            name='slogan',
            field=models.CharField(blank=True, help_text='Frase corta que aparece debajo del nombre', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='tiktok',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, help_text='Sitio web público (ej: https://miepi.com)'),
        ),
        migrations.AddField(
            model_name='company',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Número WhatsApp con código de país (ej: 527711234567)', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo principal (sidebar, login, documentos PDF)', null=True, upload_to='company/logo/'),
        ),
    ]
